name: Sync ipv6.m3u and Insert Custom Lines

on:
  schedule:
    - cron: '0 3 * * *'  # 每天日本时间中午12点执行（UTC时间03:00）
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Download upstream ipv6.m3u
        run: |
          curl -sL https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u -o ipv6.m3u

      - name: Insert custom lines from local file after 2nd line
        run: |
          head -n 1 ipv6.m3u > generated_ipv6.m3u
          cat insert_custom_lines.txt >> generated_ipv6.m3u
          tail -n +2 ipv6.m3u >> generated_ipv6.m3u

      - name: Append content from iptv.m3u (lines from 6 onward)
        run: |
          curl -sL https://raw.githubusercontent.com/Kimentanm/aptv/refs/heads/master/m3u/iptv.m3u -o iptv.m3u
          tail -n +6 iptv.m3u >> generated_ipv6.m3u

          mkdir -p generated
          mv generated_ipv6.m3u generated/ipv6_custom.m3u

      - name: Commit and Push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/ipv6_custom.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Update ipv6_custom.m3u with latest source and custom lines"
          git push
