name: Sync ipv6.m3u and Insert Custom Lines

on:
  schedule:
    - cron: "0 3 * * *" # 每天日本时间中午12点执行（UTC时间03:00）
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Download upstream file
        run: |
          curl -sL https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u -o ipv6.m3u

      - name: Insert custom lines after 3rd line
        run: |
          CUSTOM_LINE_1="#EXTINF:-1 tvg-name=\"CCTV1\" tvg-logo=\"https://live.fanmingming.cn/tv/CCTV1.png\" group-title=\"央视频道\",CCTV1备用"
          CUSTOM_LINE_2="https://rthktv33-live.akamaized.net/hls/live/2101641/RTHKTV33/stream05/streamPlaylist.m3u8"

          head -n 3 ipv6.m3u > generated_ipv6.m3u
          echo "$CUSTOM_LINE_1" >> generated_ipv6.m3u
          echo "$CUSTOM_LINE_2" >> generated_ipv6.m3u
          tail -n +4 ipv6.m3u >> generated_ipv6.m3u

          mkdir -p generated
          mv generated_ipv6.m3u generated/ipv6_custom.m3u

      - name: Commit and Push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/ipv6_custom.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Update ipv6_custom.m3u with latest source and custom lines"
          git push
